#!/bin/bash

R="\e[31m"
G="\e[32m"
Y="\[e33m"
Normal="\e[0m"



LOGS_FOLDER="/var/log/shell-practicing"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 ) # $0 --> Current file name  --> 14-logs
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER  # -p means if directory is not there it creates if directory is there is keeps quiet
echo "Script started executed at: $(date)" | tee -a $LOG_FILE  # tee command appends the output printing of this command on mobexterm same in LOg file as well.


mkdir -p $LOGS_FOLDER
echo "Script started executed at: $(date)" | tee -a $LOG_FILE

SOURCE_DIR=/home/ec2-user/app-logsss

if [ ! -d $SOURCE_DIR ]; then
    echo -e "ERROR:: $SOURCE_DIR does not exist"
    exit 1
fi
FILES_TO_DELETE=$(find $SOURCE_DIR -name "*.log" -type -f -mtime +14)

while IFS= read -r filepath
do
    echo "Deleting the file:$filepath"
    rm -rf $filepath
    echo "Deleting the file: $filepath"
done <<< $FILES_TO_DELETE














